name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  file_picker: ^5.5.0
  file_manager: ^1.0.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  open_file: ^3.5.10
  share_plus: ^10.1.3
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/     # Corrected assets path  

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/font/poppins/Poppins-Regular.ttf
        - asset: lib/assets/font/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/font/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/font/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/font/poppins/Poppins-Italic.ttf
          style: italic